name: quant-finance-progs CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    name: Python ${{ matrix.python-version }} Lint & Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Lint with Ruff
        run: poetry run ruff .

      - name: Sort imports with isort
        run: poetry run isort . --check-only --diff

      - name: Check formatting with Black
        run: poetry run black . --check

      - name: Static type check with MyPy
        run: poetry run mypy .

      - name: Run tests with Pytest
        run: poetry run pytest
